services:
  db:
    image: postgres:16-alpine
    container_name: siprima-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: siprima_pas
      POSTGRES_USER: siprima
      POSTGRES_PASSWORD: siprima_dev_change_me
    ports:
      - "5432:5432"
    volumes:
      - siprima_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U siprima -d siprima_pas"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  siprima_pgdata:
