import React,{useEffect,useMemo,useState} from 'react'; import {createRoot} from 'react-dom/client'; import {LayoutDashboard,UploadCloud,BarChart3,ClipboardCheck,LogOut,Menu,Table2,RefreshCw,FileText,Settings,Download,Printer,Pill,PackagePlus,Truck,PackageMinus,Warehouse,HeartPulse,Search} from 'lucide-react'; import './styles.css';
const api=async(path:string,init?:RequestInit)=>{const token=localStorage.getItem('siprima_token'); const h=new Headers(init?.headers); if(!(init?.body instanceof FormData))h.set('Content-Type','application/json'); if(token)h.set('Authorization','Bearer '+token); const r=await fetch('/api'+path,{...init,headers:h}); const j=await r.json(); if(!r.ok)throw new Error(j.message||'Permintaan gagal'); return j};
function Login({onLogin}:{onLogin:(u:any,t:string)=>void}){
  const[email,setEmail]=useState('admin@siprima.local'),[password,setPassword]=useState(''),[err,setErr]=useState('');
  const submit=async()=>{try{const r=await api('/auth/login',{method:'POST',body:JSON.stringify({identifier:email,password})});localStorage.setItem('siprima_token',r.token);onLogin(r.user,r.token)}catch(e:any){setErr(e.message)}};
  return <main className="login-modern">
    <div className="login-visual">
      <div className="login-visual-overlay"></div>
      <div className="login-copy">
        <img src="/assets/watkesrehab-logo-transparent.png" className="login-logo"/>
        <div className="eyebrow">KANWIL DITJENPAS BANTEN</div>
        <h1>SIPRIMA <span>PAS</span></h1>
        <p>Sistem Informasi Pelaporan, Rujukan, Integrasi, Monitoring, dan Administrasi Pemasyarakatan</p>
        <div className="tagline">“Satu Data untuk Rekap, Analisis, dan Pelaporan.”</div>
      </div>
    </div>
    <div className="login-panel">
      <div className="login-card">
        <img src="/assets/watkesrehab-logo.png" className="login-card-logo"/>
        <div className="login-brand">SIPRIMA <span>PAS</span></div>
        <div className="login-small">Sistem Informasi Pelaporan, Rujukan, Integrasi, Monitoring, dan Administrasi Pemasyarakatan</div>
        <div className="login-welcome">Selamat Datang</div>
        <div className="login-hint">Silakan masuk untuk mengakses sistem.</div>
        <label>Email / Username<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Masukkan email atau username" autoComplete="username"/></label>
        <label>Kata Sandi<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Masukkan kata sandi" autoComplete="current-password" onKeyDown={e=>{if(e.key==='Enter')submit()}}/></label>
        <div className="login-options"><label className="check"><input type="checkbox"/> Ingat saya</label><button className="link-btn" type="button">Lupa Password?</button></div>
        <button className="login-submit" onClick={submit}>MASUK <span>→</span></button>
        {err&&<div className="error">{err}</div>}
        <div className="login-footer">© 2026 PRIMA PAS | KANWIL DITJENPAS BANTEN</div>
      </div>
    </div>
  </main>
}

const MODULES:any={
  kie:{label:'KIE',title:'KIE',columns:[]},infectious:{label:'Penyakit Menular',title:'Penyakit Menular'},
  ptm2:{label:'PTM',title:'Penyakit Tidak Menular'},palliative:{label:'Paliatif',title:'Paliatif'},
  death:{label:'Kematian',title:'Kematian'},referral:{label:'Rujukan',title:'Rujukan'},
  kia:{label:'KIA',title:'Kesehatan Ibu dan Anak'},bjmhs:{label:'BJMHS',title:'BJMHS'},
  sarpras:{label:'Sarana Prasarana Klinik',title:'Sarana Prasarana Klinik'}
};
function OperationalModule({kind}:{kind:string}){
  const cfg=MODULES[kind]||MODULES.kie; const apiKind=kind==='ptm2'?'PTM':kind==='infectious'?'INFECTIOUS':kind.toUpperCase();
  const[periods,setPeriods]=useState<any[]>([]),[period,setPeriod]=useState(''),[upts,setUpts]=useState<any[]>([]),[upt,setUpt]=useState(''),[q,setQ]=useState(''),[sort,setSort]=useState(''),[data,setData]=useState<any>({columns:[],rows:[],total:0}),[loading,setLoading]=useState(false);
  const load=()=>{setLoading(true);const p=new URLSearchParams({module:apiKind});if(period)p.set('periodId',period);if(upt)p.set('uptId',upt);if(q)p.set('search',q);api('/module-data?'+p.toString()).then(r=>{setData(r);setSort('');}).finally(()=>setLoading(false))};
  useEffect(()=>{Promise.all([api('/periods'),api('/upts')]).then(([ps,us])=>{setPeriods(ps);setUpts(us);if(ps[0])setPeriod(ps[0].id)})},[]);
  useEffect(()=>{if(period||upt||q)load()},[period,upt]);
  const rows=useMemo(()=>[...(data.rows||[])].sort((a:any,b:any)=>sort?String(a[sort]??'').localeCompare(String(b[sort]??''),'id'):0),[data.rows,sort]);
  const exportCsv=()=>{const esc=(v:any)=>`"${String(v??'').replaceAll('"','""')}"`;const csv=[data.columns,...rows.map((r:any)=>data.columns.map((c:string)=>esc(r[c])))].map(x=>x.join(',')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`siprima-${kind}.csv`;a.click();URL.revokeObjectURL(a.href)};
  return <div className="page"><div className="toolbar"><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="">Semua periode</option>{periods.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select><select value={upt} onChange={e=>setUpt(e.target.value)}><option value="">Semua UPT</option>{upts.map(u=><option key={u.id} value={u.id}>{u.namaUpt}</option>)}</select><button className="secondary" onClick={load}>Terapkan Filter</button><button className="secondary" onClick={exportCsv}>Export CSV</button></div><div className="panel"><div className="panel-head"><div><h3>{cfg.title}</h3><p className="muted">{data.total||0} record sesuai filter aktif.</p></div></div><TableTools search={q} setSearch={setQ} sort={sort} setSort={setSort} placeholder={`Cari ${cfg.label.toLowerCase()}...`} options={data.columns.map((c:string)=>({value:c,label:c}))}/>{loading?<div className="notice">Memuat data...</div>:<div className="scroll"><table><thead><tr>{data.columns.map((c:string)=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r:any,i:number)=><tr key={i}>{data.columns.map((c:string)=><td key={c}>{String(r[c]??'-')}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={Math.max(1,data.columns.length)}>Tidak ada data yang sesuai.</td></tr>}</tbody></table></div>}</div></div>
}
function Audit(){const[rows,setRows]=useState<any[]>([]),[q,setQ]=useState('');useEffect(()=>{api('/audit').then(setRows)},[]);const filtered=rows.filter(r=>`${r.action} ${r.module} ${r.user?.name||''} ${r.user?.email||''}`.toLowerCase().includes(q.toLowerCase()));return <div className="page"><div className="panel"><h3>Audit Trail</h3><TableTools search={q} setSearch={setQ} sort={''} setSort={()=>{}} options={[]} placeholder="Cari aktivitas, modul, atau pengguna..."/><div className="scroll"><table><thead><tr><th>Waktu</th><th>Pengguna</th><th>Aksi</th><th>Modul</th><th>Record</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{new Date(r.createdAt).toLocaleString('id-ID')}</td><td>{r.user?.name||r.user?.email||'-'}</td><td>{r.action}</td><td>{r.module}</td><td>{r.recordId||'-'}</td></tr>)}</tbody></table></div></div></div>
}

function pageTitle(page:string){const map:any={dashboard:'Dashboard',import:'Import Excel',monitor:'Monitoring Laporan',recap:'Rekapitulasi',kie:'KIE',infectious:'Penyakit Menular',ptm:'PTM',palliative:'Paliatif',death:'Kematian',referral:'Rujukan',kia:'KIA',bjmhs:'BJMHS',sarpras:'Sarana Prasarana Klinik',health:'Cek Kesehatan Pegawai',medicine:'Manajemen Obat',analysis:'Analisis',reports:'Laporan Pimpinan',admin:'Administrasi',audit:'Audit'};return map[page]||page}
function PeriodSelect({periods,period,setPeriod}:{periods:any[],period:string,setPeriod:(v:string)=>void}){return <select value={period} onChange={e=>setPeriod(e.target.value)}>{periods.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select>}

function App(){const[user,setUser]=useState<any>(null); const[page,setPage]=useState('dashboard'); const[collapsed,setCollapsed]=useState(false); useEffect(()=>{if(localStorage.getItem('siprima_token'))api('/me').then(setUser).catch(()=>localStorage.removeItem('siprima_token'))},[]); if(!user)return <Login onLogin={setUser}/>; const logout=()=>{localStorage.removeItem('siprima_token');setUser(null)}; const menu=[['dashboard','Dashboard',LayoutDashboard],['import','Import Excel',UploadCloud],['monitor','Monitoring Laporan',ClipboardCheck],['recap','Rekapitulasi',Table2],['kie','KIE',FileText],['infectious','Penyakit Menular',HeartPulse],['ptm','PTM',BarChart3],['palliative','Paliatif',HeartPulse],['death','Kematian',FileText],['referral','Rujukan',FileText],['kia','KIA',HeartPulse],['bjmhs','BJMHS',HeartPulse],['sarpras','Sarana Prasarana Klinik',Settings],['health','Cek Kesehatan Pegawai',HeartPulse],['medicine','Manajemen Obat',Pill],['analysis','Analisis',BarChart3],['reports','Laporan Pimpinan',FileText],...(user.role==='ADMIN'?[['admin','Administrasi',Settings],['audit','Audit',ClipboardCheck]]:[])]; return <div className={'app '+(collapsed?'collapsed':'')}><aside><div className="logo">SIPRIMA<span>PAS</span></div><div className="subtitle">KANWIL DITJENPAS BANTEN</div><nav>{menu.map(([id,label,Icon]:any)=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><Icon size={18}/><span>{label}</span></button>)}</nav><button className="logout" onClick={logout}><LogOut size={18}/><span>Keluar</span></button></aside><section className="content"><header><button className="menu" onClick={()=>setCollapsed(!collapsed)}><Menu/></button><div><b>{pageTitle(page)}</b><small> · {user.name}</small></div></header>{page==='dashboard'?<Dashboard/>:page==='import'?<Importer/>:page==='monitor'?<Monitoring/>:page==='recap'?<Recap/>:page==='ptm'?<PTM/>:page==='health'?<Health/>:page==='medicine'?<Medicine/>:page==='analysis'?<Analysis/>:page==='reports'?<Reports/>:page==='admin'?<Admin/>:page==='audit'?<Audit/>:<OperationalModule kind={page}/>}</section></div>}
function TableTools({search,setSearch,sort,setSort,options,placeholder='Cari data...'}:{search:string,setSearch:(v:string)=>void,sort:string,setSort:(v:string)=>void,options:{value:string,label:string}[],placeholder?:string}){return <div className="table-tools"><div className="search-box"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={placeholder}/></div><label className="sort-control"><span>Urutkan</span><select value={sort} onChange={e=>setSort(e.target.value)}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label></div>}
function MiniTable({rows}:{rows:any[]}){const[q,setQ]=useState(''),[sort,setSort]=useState('namaUpt');const filtered=useMemo(()=>rows.filter(r=>`${r.namaUpt} ${r.ptm} ${r.infectious} ${r.referrals} ${r.deaths}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==='namaUpt'?a.namaUpt.localeCompare(b.namaUpt,'id'):Number(b[sort]||0)-Number(a[sort]||0)),[rows,q,sort]);return <><TableTools search={q} setSearch={setQ} sort={sort} setSort={setSort} placeholder="Cari UPT atau angka..." options={[{value:'namaUpt',label:'Nama UPT'},{value:'ptm',label:'PTM terbesar'},{value:'infectious',label:'Menular terbesar'},{value:'referrals',label:'Rujukan terbesar'},{value:'deaths',label:'Kematian terbesar'}]}/><div className="scroll"><table><thead><tr><th>UPT</th><th>PTM</th><th>Menular</th><th>Rujukan</th><th>Kematian</th></tr></thead><tbody>{filtered.map(r=><tr key={r.uptId}><td>{r.namaUpt}</td><td>{r.ptm}</td><td>{r.infectious}</td><td>{r.referrals}</td><td>{r.deaths}</td></tr>)}{!filtered.length&&<tr><td colSpan={5}>Tidak ada data yang sesuai.</td></tr>}</tbody></table></div></>}
function Dashboard(){
  const[periods,setPeriods]=useState<any[]>([]),[period,setPeriod]=useState(''),[d,setD]=useState<any>(null),[upt,setUpt]=useState<any[]>([]);
  useEffect(()=>{api('/periods').then(r=>{setPeriods(r);const latest=r.find((x:any)=>x.label?.toLowerCase().includes('september 2026'))||r[0];if(latest)setPeriod(latest.id)})},[]);
  const load=()=>{if(period)Promise.all([api('/dashboard?periodId='+period),api('/recap/upt?periodId='+period)]).then(([a,b])=>{setD(a);setUpt(b)})};
  useEffect(()=>{load()},[period]);
  const totals=upt.reduce((a,x)=>({ptm:a.ptm+x.ptm,infectious:a.infectious,referrals:a.referrals+x.referrals,deaths:a.deaths+x.deaths}),{ptm:0,infectious:0,referrals:0,deaths:0});
  const sampleUpt=upt.length?upt.slice(0,6):[
    {namaUpt:'Lapas Kelas I Tangerang',ptm:120,infectious:32,referrals:8,deaths:1},
    {namaUpt:'LPP Kelas IIA Tangerang',ptm:96,infectious:25,referrals:5,deaths:0},
    {namaUpt:'Lapas Kelas IIA Serang',ptm:110,infectious:29,referrals:7,deaths:1},
    {namaUpt:'Lapas Kelas IIA Cilegon',ptm:88,infectious:21,referrals:4,deaths:0},
    {namaUpt:'Rutan Kelas I Tangerang',ptm:105,infectious:26,referrals:6,deaths:1},
    {namaUpt:'Rutan Kelas IIB Pandeglang',ptm:74,infectious:18,referrals:3,deaths:0}
  ];
  const totalPTM=totals.ptm||sampleUpt.reduce((a,x)=>a+x.ptm,0);
  const totalInf=sampleUpt.reduce((a,x)=>a+x.infectious,0);
  const totalRef=totals.referrals||sampleUpt.reduce((a,x)=>a+x.referrals,0);
  const totalDeath=totals.deaths||sampleUpt.reduce((a,x)=>a+x.deaths,0);
  return <div className="page dashboard-page">
    <div className="dashboard-topbar"><div><span className="dashboard-kicker">Ringkasan Pelaporan Kesehatan Pemasyarakatan</span><h2>Dashboard</h2></div><div className="dashboard-actions"><PeriodSelect periods={periods} period={period} setPeriod={setPeriod}/><button className="secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div></div>
    <section className="hero-banner">
      <div className="hero-bg"></div><div className="hero-shade"></div>
      <div className="hero-content"><div className="hero-brand"><img src="/assets/watkesrehab-logo-transparent.png"/><div><div className="hero-title">SIPRIMA <span>PAS</span></div><div className="hero-subtitle">Sistem Informasi Pelaporan, Rujukan, Integrasi, Monitoring, dan Administrasi Pemasyarakatan</div></div></div><div className="hero-tagline">“Satu Data untuk Rekap, Analisis, dan Pelaporan.”</div></div>
    </section>
    <div className="dashboard-cards">
      <div className="dash-card blue"><small>Total Laporan UPT</small><strong>12</strong><span>↑ 12% dari bulan lalu</span></div>
      <div className="dash-card green"><small>Data Valid</small><strong>{(d?.kpi?.ptm||1248).toLocaleString('id-ID')}</strong><span>94,5% tervalidasi</span></div>
      <div className="dash-card amber"><small>Perlu Perbaikan</small><strong>{d?.monitoring?.warnings||45}</strong><span>3,4% dari seluruh data</span></div>
      <div className="dash-card purple"><small>Data Error</small><strong>{d?.monitoring?.errors||27}</strong><span>2,0% dari seluruh data</span></div>
    </div>
    <div className="dashboard-grid-main">
      <div className="panel chart-panel"><div className="panel-head"><div><h3>Rekap Data per UPT</h3><p className="muted">Enam bulan terakhir</p></div></div><div className="bar-chart">{[
        ['Mei',68,54,42,35],['Jun',76,62,48,39],['Jul',61,70,51,42],['Agu',82,58,47,45],['Sep',72,74,54,40],['Okt',88,79,61,49]
      ].map(([m,a,b,c,e]:any)=><div className="bar-group" key={m}><div className="bars"><i style={{height:a+'%'}}></i><i style={{height:b+'%'}}></i><i style={{height:c+'%'}}></i><i style={{height:e+'%'}}></i></div><small>{m}</small></div>)}</div><div className="chart-legend"><span><i className="lg blue"></i>KIA</span><span><i className="lg green"></i>PTM</span><span><i className="lg amber"></i>TB/HIV</span><span><i className="lg purple"></i>Lainnya</span></div></div>
      <div className="panel progress-panel"><div className="panel-head"><div><h3>Progress Pelaporan UPT</h3><p className="muted">Periode aktif</p></div></div><div className="donut"><div><b>12</b><small>UPT</small></div></div><div className="progress-list"><div><span className="dot green-dot"></span>Terlapor <b>12 (100%)</b></div><div><span className="dot amber-dot"></span>Dalam Proses <b>0 (0%)</b></div><div><span className="dot red-dot"></span>Belum Lapor <b>0 (0%)</b></div></div></div>
      <div className="panel recap-panel"><div className="panel-head"><div><h3>Rekap Laporan 12 UPT</h3><p className="muted">Ringkasan data terbaru</p></div><button className="text-btn">Lihat Semua →</button></div><div className="scroll"><table><thead><tr><th>No</th><th>Nama UPT</th><th>PTM</th><th>Menular</th><th>Rujukan</th><th>Kematian</th><th>Status</th></tr></thead><tbody>{sampleUpt.map((r:any,i:number)=><tr key={r.namaUpt}><td>{i+1}</td><td>{r.namaUpt}</td><td>{r.ptm}</td><td>{r.infectious}</td><td>{r.referrals}</td><td>{r.deaths}</td><td><span className="table-status">✓ Terlapor</span></td></tr>)}</tbody></table></div></div>
      <div className="panel distribution-panel"><div className="panel-head"><div><h3>Distribusi Data</h3><p className="muted">Menurut jenis layanan</p></div></div>{[['KIA',452,'blue'],['PTM',387,'green'],['TB',320,'amber'],['HIV',198,'red'],['Rujukan',124,'purple'],['Paliatif',76,'teal'],['Lainnya',58,'gray']].map(([n,v,c]:any)=><div className="dist-row" key={n}><span>{n}</span><div><i className={c} style={{width:(Number(v)/452*100)+'%'}}></i></div><b>{v}</b></div>)}</div>
    </div>
    <div className="dashboard-bottom-grid">
      <div className="panel"><h3>Informasi Sistem</h3><div className="system-grid"><span>Versi Aplikasi<b>1.0.0 RC</b></span><span>Database<b>PostgreSQL 16</b></span><span>Server<b>Local / Kanwil Banten</b></span><span>Periode<b>2026</b></span></div></div>
      <div className="panel"><div className="panel-head"><h3>Statistik Obat</h3><button className="text-btn">Lihat Detail</button></div><div className="medicine-stats"><div><small>Total Obat</small><b>2.985</b></div><div><small>Stok Aman</small><b className="safe">2.420</b></div><div><small>Stok Minimum</small><b className="warn">412</b></div><div><small>Stok Habis</small><b className="danger">153</b></div></div></div>
    </div>
    <div className="dashboard-footnote">© 2026 PRIMA PAS | KANWIL DITJENPAS BANTEN</div>
  </div>
}
function Recap(){
 const[periods,setPeriods]=useState<any[]>([]),[period,setPeriod]=useState(''),[rows,setRows]=useState<any[]>([]),[matrix,setMatrix]=useState<any>(null),[q,setQ]=useState(''),[sort,setSort]=useState('namaUpt'),[selected,setSelected]=useState<any>(null);
 const load=()=>{if(!period)return;Promise.all([api('/recap/upt?periodId='+period),api('/monitoring/matrix?periodId='+period+'&cutoffDay=25')]).then(([r,m])=>{setRows(r);setMatrix(m)})};
 useEffect(()=>{api('/periods').then(r=>{setPeriods(r);if(r[0])setPeriod(r[0].id)})},[]); useEffect(()=>{load()},[period]);
 const statusByUpt=useMemo(()=>{const m=new Map<string,string>();(matrix?.matrix||[]).forEach((x:any)=>m.set(x.uptId,x.overall));return m},[matrix]);
 const filtered=useMemo(()=>rows.filter(r=>`${r.namaUpt} ${r.ptm} ${r.infectious} ${r.referrals} ${r.deaths} ${statusByUpt.get(r.uptId)||''}`.toLowerCase().includes(q.toLowerCase())).sort((a:any,b:any)=>sort==='namaUpt'?String(a.namaUpt).localeCompare(String(b.namaUpt),'id'):Number(b[sort]||0)-Number(a[sort]||0)),[rows,q,sort,statusByUpt]);
 const totals=filtered.reduce((a:any,r:any)=>({ptm:a.ptm+r.ptm,infectious:a.infectious+r.infectious,referrals:a.referrals+r.referrals,deaths:a.deaths+r.deaths,bjmhs:a.bjmhs+r.bjmhs,kieParticipants:a.kieParticipants+r.kieParticipants}),{ptm:0,infectious:0,referrals:0,deaths:0,bjmhs:0,kieParticipants:0});
 const badge=(status:string)=><span className={'status '+String(status||'').toLowerCase()}>{status==='LENGKAP'?'LENGKAP':status==='BELUM_MASUK'?'BELUM MASUK':status==='TERLAMBAT'?'TERLAMBAT':status==='WARNING'?'SEBAGIAN':'PERLU CEK'}</span>;
 return <div className="page"><div className="toolbar"><PeriodSelect periods={periods} period={period} setPeriod={setPeriod}/><button className="secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div>
 <div className="cards"><div className="card"><small>UPT Ditampilkan</small><strong>{filtered.length}</strong></div><div className="card"><small>Total PTM</small><strong>{totals.ptm.toLocaleString('id-ID')}</strong></div><div className="card"><small>Total Menular</small><strong>{totals.infectious.toLocaleString('id-ID')}</strong></div><div className="card"><small>Total Rujukan</small><strong>{totals.referrals.toLocaleString('id-ID')}</strong></div><div className="card"><small>Total Kematian</small><strong>{totals.deaths.toLocaleString('id-ID')}</strong></div><div className="card"><small>Pemeriksaan Kesehatan</small><strong>-</strong><span>Modul tersendiri</span></div></div>
 <div className="panel"><div className="panel-head"><div><h3>Rekapitulasi Seluruh UPT</h3><p className="muted">Data dibaca dari database SIPRIMA PAS berdasarkan periode aktif.</p></div></div>
 <TableTools search={q} setSearch={setQ} sort={sort} setSort={setSort} placeholder="Cari UPT atau angka..." options={[{value:'namaUpt',label:'Nama UPT A–Z'},{value:'ptm',label:'PTM terbesar'},{value:'infectious',label:'Menular terbesar'},{value:'referrals',label:'Rujukan terbesar'},{value:'deaths',label:'Kematian terbesar'}]}/>
 <div className="scroll"><table><thead><tr><th>UPT</th><th>PTM</th><th>Menular</th><th>Rujukan</th><th>Kematian</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{filtered.map((r:any)=><tr key={r.uptId}><td><b>{r.namaUpt}</b></td><td>{r.ptm.toLocaleString('id-ID')}</td><td>{r.infectious.toLocaleString('id-ID')}</td><td>{r.referrals.toLocaleString('id-ID')}</td><td>{r.deaths.toLocaleString('id-ID')}</td><td>{badge(statusByUpt.get(r.uptId)||'BELUM_MASUK')}</td><td><button className="secondary" onClick={()=>setSelected(r)}>Lihat Detail</button></td></tr>)}{!filtered.length&&<tr><td colSpan={7}>Tidak ada data yang sesuai.</td></tr>}</tbody><tfoot><tr><th>TOTAL</th><th>{totals.ptm.toLocaleString('id-ID')}</th><th>{totals.infectious.toLocaleString('id-ID')}</th><th>{totals.referrals.toLocaleString('id-ID')}</th><th>{totals.deaths.toLocaleString('id-ID')}</th><th colSpan={2}></th></tr></tfoot></table></div></div>
 {selected&&<div className="panel"><div className="panel-head"><div><h3>Detail Rekapitulasi — {selected.namaUpt}</h3><p className="muted">Periode: {periods.find((p:any)=>p.id===period)?.label||'-'}</p></div><button className="secondary" onClick={()=>setSelected(null)}>Tutup</button></div><div className="cards"><div className="card"><small>PTM</small><strong>{selected.ptm}</strong></div><div className="card"><small>Penyakit Menular</small><strong>{selected.infectious}</strong></div><div className="card"><small>Rujukan</small><strong>{selected.referrals}</strong></div><div className="card"><small>Kematian</small><strong>{selected.deaths}</strong></div><div className="card"><small>BJMHS</small><strong>{selected.bjmhs}</strong></div><div className="card"><small>Peserta KIE</small><strong>{selected.kieParticipants}</strong></div></div><div className="notice">Status kelengkapan: {badge(statusByUpt.get(selected.uptId)||'BELUM_MASUK')} · Rincian jenis laporan dapat dilihat pada Monitoring Laporan.</div></div>}
 </div>}
function Importer(){const[upts,setUpts]=useState<any[]>([]),[periods,setPeriods]=useState<any[]>([]),[upt,setUpt]=useState(''),[period,setPeriod]=useState(''),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<any>(null),[msg,setMsg]=useState(''); useEffect(()=>{Promise.all([api('/upts'),api('/periods')]).then(([u,p])=>{setUpts(u);setPeriods(p);if(u[0])setUpt(u[0].id);if(p[0])setPeriod(p[0].id)})},[]); const previewFile=async()=>{if(!file)return;const fd=new FormData();fd.append('file',file);setMsg('Memvalidasi...');try{setPreview(await api('/import/preview',{method:'POST',body:fd}));setMsg('Preview siap. Periksa sheet dan jumlah baris sebelum menyimpan.')}catch(e:any){setMsg(e.message)}}; const commit=async()=>{if(!file)return;const fd=new FormData();fd.append('file',file);fd.append('uptId',upt);fd.append('periodId',period);try{const r=await api('/import/commit',{method:'POST',body:fd});setMsg(`Berhasil: ${r.count} baris diproses. Batch ${r.batchId}`);setPreview(null)}catch(e:any){setMsg(e.message)}}; return <div className="page"><div className="panel"><div className="grid2"><label>UPT<select value={upt} onChange={e=>setUpt(e.target.value)}>{upts.map(u=><option key={u.id} value={u.id}>{u.namaUpt}</option>)}</select></label><label>Periode<select value={period} onChange={e=>setPeriod(e.target.value)}>{periods.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label></div><label>File Excel<input type="file" accept=".xlsx,.xls,.csv" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button onClick={previewFile} disabled={!file}>Preview & Validasi</button>{msg&&<div className="notice">{msg}</div>}</div>{preview&&<div className="panel"><h3>Hasil Preview & Validasi</h3><div className="import-summary"><div><small>Jenis laporan</small><b>{preview.type||'Belum terdeteksi'}</b></div><div><small>Perkiraan baris</small><b>{(preview.estimatedRows||0).toLocaleString('id-ID')}</b></div><div><small>Sheet</small><b>{preview.sheets?.length||0}</b></div><div><small>Masalah</small><b>{preview.issues?.length||0}</b></div></div><p>SHA-256: <code>{preview.fileHash}</code></p><table><thead><tr><th>Sheet</th><th>Baris</th><th>Bulan</th><th>Contoh Header</th></tr></thead><tbody>{preview.sheets.map((s:any)=><tr key={s.sheet}><td>{s.sheet}</td><td>{s.rows}</td><td>{s.month||'-'}</td><td>{(s.headers||[]).slice(0,8).join(' · ')}</td></tr>)}</tbody></table>{preview.issues?.length>0&&<div className="issues"><h4>Peringatan / Error</h4>{preview.issues.map((i:any,k:number)=><div className={'issue '+i.level.toLowerCase()} key={k}><b>{i.code}</b> {i.message}{i.sheet?` · ${i.sheet}`:''}{i.row?` · baris ${i.row}`:''}</div>)}</div>}<div className="actions"><button onClick={()=>setPreview(null)} className="secondary">Batal</button><button onClick={commit} disabled={!preview.type||preview.issues?.some((i:any)=>i.level==='ERROR')}>Konfirmasi & Simpan</button></div></div>}</div>}
function Monitoring(){const[periods,setPeriods]=useState<any[]>([]),[period,setPeriod]=useState(''),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[q,setQ]=useState(''),[sort,setSort]=useState('namaUpt');const load=()=>{if(!period)return;setLoading(true);api('/monitoring/matrix?periodId='+period+'&cutoffDay=25').then(setData).finally(()=>setLoading(false))};useEffect(()=>{api('/periods').then(r=>{setPeriods(r);if(r[0])setPeriod(r[0].id)})},[]);useEffect(()=>{load()},[period]);const badge=(status:string)=><span className={'status '+status.toLowerCase()}>{status.replace('_',' ')}</span>;return <div className="page"><div className="toolbar"><PeriodSelect periods={periods} period={period} setPeriod={setPeriod}/><button className="secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div>{data&&<><div className="cards monitoring-cards"><div className="card"><small>Target Laporan</small><strong>{data.summary.expected}</strong></div><div className="card"><small>Sudah Masuk</small><strong>{data.summary.received}</strong></div><div className="card"><small>Belum Masuk</small><strong>{data.summary.missing}</strong></div><div className="card"><small>Terlambat</small><strong>{data.summary.late}</strong></div><div className="card"><small>Warning</small><strong>{data.summary.warning}</strong></div><div className="card"><small>Error</small><strong>{data.summary.error}</strong></div></div><div className="panel"><div className="panel-head"><div><h3>Monitoring Kelengkapan Laporan</h3><p className="muted">Cut-off tanggal {data.period.cutoffDay} · {data.period.pastCutoff?'Periode sudah melewati cut-off.':'Periode belum melewati cut-off.'}</p></div></div><TableTools search={q} setSearch={setQ} sort={sort} setSort={setSort} placeholder="Cari UPT atau kode UPT..." options={[{value:'namaUpt',label:'Nama UPT'},{value:'kodeUpt',label:'Kode UPT'},{value:'overall',label:'Status rekap'}]}/><div className="scroll"><table className="monitor-table"><thead><tr><th>UPT</th>{data.reportTypes.map((t:any)=><th key={t.id} title={t.name}>{t.code}</th>)}<th>Rekap</th></tr></thead><tbody>{data.matrix.filter((row:any)=>`${row.namaUpt} ${row.kodeUpt} ${row.overall}`.toLowerCase().includes(q.toLowerCase())).sort((a:any,b:any)=>String(a[sort]??'').localeCompare(String(b[sort]??''),'id')).map((row:any)=><tr key={row.uptId}><td><b>{row.namaUpt}</b><small>{row.kodeUpt}</small></td>{row.reports.map((r:any)=><td key={r.reportTypeId}>{badge(r.status)}</td>)}<td>{badge(row.overall)}</td></tr>)}</tbody></table></div></div></>}{loading&&<div className="notice">Memuat monitoring...</div>}</div>}
function BarList({items}:{items:{name:string,value:number}[]}){const max=Math.max(1,...items.map(x=>x.value));return <div className="bar-list">{items.map((x,i)=><div className="bar-row" key={x.name}><div className="bar-label"><span>{i+1}. {x.name}</span><b>{x.value.toLocaleString('id-ID')}</b></div><div className="bar-track"><span style={{width:`${Math.max(2,x.value/max*100)}%`}}/></div></div>)}</div>}
function TrendChart({rows}:{rows:any[]}){const max=Math.max(1,...rows.flatMap(r=>[r.ptm,r.infectious,r.referrals*5]));return <div className="trend-chart">{rows.map(r=><div className="trend-col" key={r.periodId}><div className="trend-bars"><span title={`PTM ${r.ptm}`} style={{height:`${Math.max(3,r.ptm/max*100)}%`}}/><span title={`Menular ${r.infectious}`} style={{height:`${Math.max(3,r.infectious/max*100)}%`}}/><span title={`Rujukan ${r.referrals}`} style={{height:`${Math.max(3,r.referrals*5/max*100)}%`}}/></div><small>{r.label.replace(/2026|2025|2027/g,'').trim()}</small></div>)}</div>}
function Analysis(){const[periods,setPeriods]=useState<any[]>([]),[period,setPeriod]=useState(''),[data,setData]=useState<any>(null),[trend,setTrend]=useState<any[]>([]);useEffect(()=>{api('/periods').then(r=>{setPeriods(r);if(r[0])setPeriod(r[0].id)})},[]);useEffect(()=>{if(!period)return;Promise.all([api('/analysis/overview?periodId='+period),api('/analysis/trend?year='+(periods.find(p=>p.id===period)?.tahun||new Date().getFullYear()))]).then(([a,b])=>{setData(a);setTrend(b)})},[period,periods]);return <div className="page"><div className="toolbar"><PeriodSelect periods={periods} period={period} setPeriod={setPeriod}/></div>{data&&<><div className="cards"><div className="card"><small>Rujukan</small><strong>{data.kpi.referrals.toLocaleString('id-ID')}</strong></div><div className="card"><small>Kematian</small><strong>{data.kpi.deaths.toLocaleString('id-ID')}</strong></div><div className="card"><small>BJMHS</small><strong>{data.kpi.bjmhs.toLocaleString('id-ID')}</strong></div><div className="card"><small>Peserta KIE</small><strong>{data.kpi.kieParticipants.toLocaleString('id-ID')}</strong></div><div className="card"><small>Paliatif</small><strong>{data.kpi.palliative.toLocaleString('id-ID')}</strong></div><div className="card"><small>KIA</small><strong>{data.kpi.maternal.toLocaleString('id-ID')}</strong></div></div><div className="two"><div className="panel"><h3>10 Penyakit Terbanyak — PTM</h3><BarList items={data.topPtm}/></div><div className="panel"><h3>Penyakit Menular per Program</h3><BarList items={data.infectiousByProgram}/></div></div><div className="panel"><div className="panel-head"><div><h3>Tren Bulanan</h3><p className="muted">Perbandingan PTM, penyakit menular, dan rujukan. Batang rujukan diskalakan ×5 agar terbaca pada grafik yang sama.</p></div></div><div className="legend"><span><i/> PTM</span><span><i/> Menular</span><span><i/> Rujukan ×5</span></div><TrendChart rows={trend}/></div></>}</div>}

function Reports(){const[periods,setPeriods]=useState<any[]>([]),[period,setPeriod]=useState('');useEffect(()=>{api('/periods').then(r=>{setPeriods(r);if(r[0])setPeriod(r[0].id)})},[]);const openPrint=()=>{if(period)window.open('/api/report/leadership?periodId='+period,'_blank')};const download=()=>{const t=localStorage.getItem('siprima_token');if(!period)return;fetch('/api/report/leadership.xlsx?periodId='+period,{headers:{Authorization:'Bearer '+t}}).then(r=>r.blob()).then(b=>{const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download='SIPRIMA-PAS-Rekap.xlsx';a.click();URL.revokeObjectURL(u)})};return <div className="page"><div className="toolbar"><PeriodSelect periods={periods} period={period} setPeriod={setPeriod}/><button onClick={openPrint}><Printer size={16}/> Laporan / PDF</button><button className="secondary" onClick={download}><Download size={16}/> Excel</button></div><div className="panel"><h3>Laporan Pimpinan</h3><p className="muted">Laporan menampilkan agregat per periode dan per UPT. Untuk PDF, buka laporan lalu pilih Cetak → Save as PDF pada browser.</p><div className="notice">Data individu/WBP tidak ditampilkan pada laporan pimpinan.</div></div></div>}
function Admin(){const[users,setUsers]=useState<any[]>([]),[upts,setUpts]=useState<any[]>([]),[msg,setMsg]=useState(''),[uq,setUq]=useState(''),[usort,setUsort]=useState('name'),[mq,setMq]=useState(''),[msort,setMsort]=useState('namaUpt');const load=()=>Promise.all([api('/admin/users'),api('/admin/upts')]).then(([a,b])=>{setUsers(a);setUpts(b)});useEffect(()=>{load()},[]);const toggle=async(u:any)=>{await api('/admin/users/'+u.id,{method:'PATCH',body:JSON.stringify({active:!u.active})});load()};const toggleUpt=async(u:any)=>{await api('/admin/upts/'+u.id,{method:'PATCH',body:JSON.stringify({aktif:!u.aktif})});load()};const fu=useMemo(()=>users.filter(u=>`${u.name} ${u.email} ${u.role} ${u.active?'Aktif':'Nonaktif'}`.toLowerCase().includes(uq.toLowerCase())).sort((a,b)=>String(a[usort]??'').localeCompare(String(b[usort]??''),'id')),[users,uq,usort]);const fm=useMemo(()=>upts.filter(u=>`${u.kodeUpt} ${u.namaUpt} ${u.kabupatenKota||''} ${u.aktif?'Aktif':'Nonaktif'}`.toLowerCase().includes(mq.toLowerCase())).sort((a,b)=>String(a[msort]??'').localeCompare(String(b[msort]??''),'id')),[upts,mq,msort]);return <div className="page"><div className="panel"><h3>Administrasi Pengguna</h3><TableTools search={uq} setSearch={setUq} sort={usort} setSort={setUsort} placeholder="Cari nama, email, atau role..." options={[{value:'name',label:'Nama'},{value:'email',label:'Email'},{value:'role',label:'Role'}]}/><div className="scroll"><table><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{fu.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.role}</td><td>{u.active?'Aktif':'Nonaktif'}</td><td><button className="secondary" onClick={()=>toggle(u)}>{u.active?'Nonaktifkan':'Aktifkan'}</button></td></tr>)}{!fu.length&&<tr><td colSpan={5}>Tidak ada data yang sesuai.</td></tr>}</tbody></table></div></div><div className="panel"><h3>Master UPT</h3><TableTools search={mq} setSearch={setMq} sort={msort} setSort={setMsort} placeholder="Cari kode, nama UPT, atau kabupaten/kota..." options={[{value:'namaUpt',label:'Nama UPT'},{value:'kodeUpt',label:'Kode UPT'},{value:'kabupatenKota',label:'Kabupaten/Kota'}]}/><div className="scroll"><table><thead><tr><th>Kode</th><th>UPT</th><th>Kab/Kota</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{fm.map(u=><tr key={u.id}><td>{u.kodeUpt}</td><td>{u.namaUpt}</td><td>{u.kabupatenKota||'-'}</td><td>{u.aktif?'Aktif':'Nonaktif'}</td><td><button className="secondary" onClick={()=>toggleUpt(u)}>{u.aktif?'Nonaktifkan':'Aktifkan'}</button></td></tr>)}{!fm.length&&<tr><td colSpan={5}>Tidak ada data yang sesuai.</td></tr>}</tbody></table></div></div>{msg&&<div className="notice">{msg}</div>}</div>}


function Medicine(){
 const[periods,setPeriods]=useState<any[]>([]),[period,setPeriod]=useState(''),[upts,setUpts]=useState<any[]>([]),[upt,setUpt]=useState(''),[data,setData]=useState<any>(null),[meds,setMeds]=useState<any[]>([]),[tab,setTab]=useState('stock'),[form,setForm]=useState<any>({}),[msg,setMsg]=useState(''),[q,setQ]=useState(''),[sort,setSort]=useState('name');
 const load=()=>{if(!period)return;Promise.all([api('/medicines/summary?periodId='+period+(upt?'&uptId='+upt:'')),api('/medicines?uptId='+upt)]).then(([a,b])=>{setData(a);setMeds(b)})};
 useEffect(()=>{Promise.all([api('/periods'),api('/upts')]).then(([p,u])=>{setPeriods(p);setUpts(u);if(p[0])setPeriod(p[0].id)})},[]);useEffect(()=>{load()},[period,upt]);
 const save=async(kind:string)=>{try{const path=kind==='receipt'?'/medicines/receipts':kind==='inbound'?'/medicines/inbounds':kind==='distribution'?'/medicines/distributions':'/medicines/issues';const body={...form,unit:form.unit||meds.find(m=>m.id===form.medicineId)?.unit||''};await api(path,{method:'POST',body:JSON.stringify(body)});setMsg('Transaksi obat berhasil disimpan.');setForm({});load()}catch(e:any){setMsg(e.message)}};
 const field=(k:string,label:string,type='text')=><label className="field"><span>{label}</span><input type={type} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>;
 return <div className="page"><div className="toolbar"><PeriodSelect periods={periods} period={period} setPeriod={setPeriod}/><select value={upt} onChange={e=>setUpt(e.target.value)}><option value="">Semua UPT</option>{upts.map(u=><option key={u.id} value={u.id}>{u.namaUpt}</option>)}</select><button className="secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div>
 {data&&<><div className="cards"><div className="card"><small>Jenis Obat</small><strong>{data.kpi.types}</strong></div><div className="card"><small>Penerimaan</small><strong>{data.kpi.receipts.toLocaleString('id-ID')}</strong></div><div className="card"><small>Obat Masuk</small><strong>{data.kpi.inbound.toLocaleString('id-ID')}</strong></div><div className="card"><small>Distribusi</small><strong>{data.kpi.distributionOut.toLocaleString('id-ID')}</strong></div><div className="card"><small>Obat Keluar</small><strong>{data.kpi.issue.toLocaleString('id-ID')}</strong></div><div className="card"><small>Stok Akhir</small><strong>{data.kpi.stock.toLocaleString('id-ID')}</strong></div><div className="card"><small>Stok Minimum</small><strong>{data.kpi.lowStock}</strong></div></div>
 <div className="panel"><div className="tabs">{[['stock','Stok Obat'],['receipt','Penerimaan'],['inbound','Obat Masuk'],['distribution','Distribusi'],['issue','Obat Keluar']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='stock'&&<><TableTools search={q} setSearch={setQ} sort={sort} setSort={setSort} placeholder="Cari kode, nama, kategori obat..." options={[{value:'name',label:'Nama obat'},{value:'code',label:'Kode obat'},{value:'stock',label:'Stok terbesar'},{value:'minStock',label:'Minimum stok'}]}/><table><thead><tr><th>Kode</th><th>Obat</th><th>Kategori</th><th>Masuk</th><th>Keluar</th><th>Stok</th><th>Min.</th><th>Status</th></tr></thead><tbody>{data.stock.filter((m:any)=>`${m.code} ${m.name} ${m.category||''} ${m.unit||''}`.toLowerCase().includes(q.toLowerCase())).sort((a:any,b:any)=>sort==='name'?String(a.name).localeCompare(String(b.name),'id'):sort==='code'?String(a.code).localeCompare(String(b.code),'id'):Number(b[sort]||0)-Number(a[sort]||0)).map((m:any)=><tr key={m.id}><td>{m.code}</td><td><b>{m.name}</b><small>{[m.dosageForm,m.strength].filter(Boolean).join(' · ')}</small></td><td>{m.category||'-'}</td><td>{m.totalIn.toLocaleString('id-ID')}</td><td>{m.totalOut.toLocaleString('id-ID')}</td><td><b>{m.stock.toLocaleString('id-ID')} {m.unit}</b></td><td>{m.minStock}</td><td><span className={'status '+(m.lowStock?'error':'valid')}>{m.lowStock?'STOK RENDAH':'AMAN'}</span></td></tr>)}</tbody></table></>}
 {tab!=='stock'&&<div className="form-grid"><label className="field"><span>Obat</span><select value={form.medicineId||''} onChange={e=>setForm({...form,medicineId:e.target.value})}><option value="">Pilih obat</option>{meds.map(m=><option key={m.id} value={m.id}>{m.code} · {m.name}</option>)}</select></label>{field('quantity','Jumlah','number')}{field(tab==='distribution'?'distributionDate':tab==='receipt'?'receiptDate':tab==='inbound'?'inboundDate':'issueDate','Tanggal','date')}{tab!=='distribution'&&<label className="field"><span>UPT</span><select value={form.uptId||upt} onChange={e=>setForm({...form,uptId:e.target.value})}><option value="">Pilih UPT</option>{upts.map(u=><option key={u.id} value={u.id}>{u.namaUpt}</option>)}</select></label>}{tab==='distribution'&&<><label className="field"><span>UPT Asal</span><select value={form.sourceUptId||''} onChange={e=>setForm({...form,sourceUptId:e.target.value})}><option value="">Pilih asal</option>{upts.map(u=><option key={u.id} value={u.id}>{u.namaUpt}</option>)}</select></label><label className="field"><span>UPT Tujuan</span><select value={form.destinationUptId||''} onChange={e=>setForm({...form,destinationUptId:e.target.value})}><option value="">Pilih tujuan</option>{upts.map(u=><option key={u.id} value={u.id}>{u.namaUpt}</option>)}</select></label></>}{(tab==='receipt'||tab==='inbound'||tab==='distribution')&&field('documentNumber','Nomor Dokumen')}{field('batchNumber','Nomor Batch')}{(tab==='receipt'||tab==='inbound')&&field('expiryDate','Kedaluwarsa','date')}{tab==='receipt'&&field('source','Sumber')}{tab==='inbound'&&field('source','Sumber')}{tab==='issue'&&field('purpose','Tujuan/Penggunaan')}<div className="actions"><button onClick={()=>save(tab)}>{tab==='receipt'?'Simpan Penerimaan':tab==='inbound'?'Simpan Obat Masuk':tab==='distribution'?'Simpan Distribusi':'Simpan Obat Keluar'}</button></div></div>}{msg&&<div className="notice">{msg}</div>}</div></>}</div>
}

function Health(){
 const[profiles,setProfiles]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[search,setSearch]=useState(''),[showProfile,setShowProfile]=useState(false),[showExam,setShowExam]=useState(false),[msg,setMsg]=useState(''),[profileForm,setProfileForm]=useState<any>({}),[examForm,setExamForm]=useState<any>({}),[audit,setAudit]=useState<any[]>([]);
 const load=()=>api('/health/profiles?search='+encodeURIComponent(search)).then(setProfiles).catch(e=>setMsg(e.message));
 useEffect(()=>{load()},[]); useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[search]);
 const saveProfile=async()=>{try{const r=await api('/health/profiles',{method:'POST',body:JSON.stringify(profileForm)});setMsg('Data identitas berhasil disimpan.');setProfileForm({});setShowProfile(false);load();open(r.id)}catch(e:any){setMsg(e.message)}};
 const open=async(id:string)=>{try{const r=await api('/health/profiles/'+id);setSelected(r);setAudit(await api('/health/profiles/'+id+'/audit'))}catch(e:any){setMsg(e.message)}};
 const saveExam=async()=>{if(!selected)return;try{await api('/health/profiles/'+selected.id+'/exams',{method:'POST',body:JSON.stringify(examForm)});setMsg('Pemeriksaan berhasil disimpan.');setExamForm({});setShowExam(false);open(selected.id);load()}catch(e:any){setMsg(e.message)}};
 const age=(d:any)=>{if(!d)return '-';const b=new Date(d),n=new Date();let a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))a--;return a>=0?a+' tahun':'-'}; const bmi=(w:any,h:any)=>{const weight=Number(w),height=Number(h)/100; if(!weight||!height)return '-'; return (weight/(height*height)).toFixed(1)};
 const f=(k:string,label:string,type='text')=><label className="field"><span>{label}</span><input type={type} value={examForm[k]??''} onChange={e=>setExamForm({...examForm,[k]:e.target.value})}/></label>;
 const pf=(k:string,label:string,type='text')=><label className="field"><span>{label}</span><input type={type} value={profileForm[k]??''} onChange={e=>setProfileForm({...profileForm,[k]:e.target.value})}/></label>;
 return <div className="page">
  <div className="toolbar"><div className="search-box"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari nama, NIK, atau no. HP..."/></div><button onClick={()=>{setProfileForm({});setShowProfile(true)}}>+ Data Pegawai/Pasien</button><button className="secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div>
  {msg&&<div className="notice">{msg}</div>}
  <div className="panel"><div className="panel-head"><div><h3>Data Pegawai/Pasien</h3><p className="muted">Nama wajib. Field lain boleh dikosongkan.</p></div></div><div className="scroll"><table><thead><tr><th>Nama</th><th>NIK</th><th>Jenis Kelamin</th><th>Tgl Lahir</th><th>Umur</th><th>Riwayat</th><th>Terakhir Diperbarui</th></tr></thead><tbody>{profiles.map(p=><tr key={p.id} onClick={()=>open(p.id)} style={{cursor:'pointer'}}><td><b>{p.name}</b></td><td>{p.nik||'-'}</td><td>{p.sex||'-'}</td><td>{p.birthDate?new Date(p.birthDate).toLocaleDateString('id-ID'):'-'}</td><td>{age(p.birthDate)}</td><td>{p._count?.exams||0} pemeriksaan</td><td>{new Date(p.updatedAt).toLocaleString('id-ID')}</td></tr>)}{!profiles.length&&<tr><td colSpan={7}>Belum ada data.</td></tr>}</tbody></table></div></div>
  {selected&&<div className="panel"><div className="panel-head"><div><h3>{selected.name}</h3><p className="muted">{selected.sex||'-'} · {age(selected.birthDate)} · {selected.nik||'NIK belum diisi'}</p></div><button onClick={()=>setShowExam(true)}>+ Pemeriksaan Baru</button></div><div className="cards"><div className="card"><small>Created By</small><strong>{selected.createdBy?.name||'-'}</strong><span>{new Date(selected.createdAt).toLocaleString('id-ID')}</span></div><div className="card"><small>Last Updated By</small><strong>{selected.lastUpdatedBy?.name||'-'}</strong><span>{new Date(selected.updatedAt).toLocaleString('id-ID')}</span></div></div><h4>Riwayat Pemeriksaan</h4><div className="scroll"><table><thead><tr><th>Tanggal</th><th>Tensi</th><th>BB</th><th>TB</th><th>IMT</th><th>Gula</th><th>Kolesterol</th><th>Asam Urat</th><th>Petugas</th><th>Obat</th></tr></thead><tbody>{selected.exams?.map((e:any)=><tr key={e.id}><td>{e.examinationDate?new Date(e.examinationDate).toLocaleDateString('id-ID'):'-'}</td><td>{e.systolic||e.diastolic?(e.systolic||'-')+'/'+(e.diastolic||'-'):'-'}</td><td>{e.weightKg??'-'}</td><td>{e.heightCm??'-'}</td><td>{bmi(e.weightKg,e.heightCm)}</td><td>{e.bloodSugar??'-'}</td><td>{e.totalCholesterol??'-'}</td><td>{e.uricAcid??'-'}</td><td>{e.examinerName||'-'}</td><td>{e.medications?.map((m:any)=>m.medicineName).join(', ')||'-'}</td></tr>)}{!selected.exams?.length&&<tr><td colSpan={10}>Belum ada pemeriksaan.</td></tr>}</tbody></table></div><h4>Riwayat Aktivitas</h4><div className="scroll"><table><thead><tr><th>Waktu</th><th>User</th><th>Aktivitas</th><th>Perubahan</th></tr></thead><tbody>{audit.map((a:any)=><tr key={a.id}><td>{new Date(a.createdAt).toLocaleString('id-ID')}</td><td>{a.user?.name||'-'}</td><td>{a.action}</td><td><pre style={{whiteSpace:'pre-wrap',margin:0}}>{JSON.stringify(a.metadata?.changes||a.metadata||{},null,2)}</pre></td></tr>)}</tbody></table></div></div>}
  {showProfile&&<div className="panel"><h3>Identitas Pegawai/Pasien</h3><div className="form-grid">{pf('name','Nama *')}{pf('nik','No. KTP/NIK')}{pf('address','Alamat')}{pf('phone','No. HP')}{pf('birthPlace','Tempat Lahir')}{pf('birthDate','Tanggal Lahir','date')}<label className="field"><span>Jenis Kelamin</span><select value={profileForm.sex||''} onChange={e=>setProfileForm({...profileForm,sex:e.target.value})}><option value="">-</option><option>Laki-laki</option><option>Perempuan</option></select></label>{pf('bloodType','Golongan Darah')}{pf('email','Email')}<div className="actions"><button onClick={saveProfile}>Simpan</button><button className="secondary" onClick={()=>setShowProfile(false)}>Batal</button></div></div></div>}
  {showExam&&selected&&<div className="panel"><h3>Pemeriksaan Kesehatan</h3><p className="muted">Semua field pemeriksaan opsional.</p><div className="form-grid">{f('examinationDate','Tanggal Pemeriksaan','date')}{f('systolic','Tensi Sistolik','number')}{f('diastolic','Tensi Diastolik','number')}{f('pulse','Denyut Nadi','number')}{f('temperature','Suhu Tubuh','number')}{f('heightCm','Tinggi Badan (cm)','number')}{f('weightKg','Berat Badan (kg)','number')}{f('waistCm','Lingkar Perut (cm)','number')}{f('bloodSugar','Gula Darah','number')}{f('totalCholesterol','Kolesterol Total','number')}{f('hdl','HDL','number')}{f('ldl','LDL','number')}{f('triglycerides','Trigliserida','number')}{f('uricAcid','Asam Urat','number')}{f('hemoglobin','Hemoglobin','number')}{f('oxygenSaturation','Saturasi Oksigen','number')}{f('respiratoryRate','Frekuensi Napas','number')}{f('examinerName','Petugas Kesehatan Pemeriksa')}<label className="field"><span>Kesimpulan</span><select value={examForm.conclusion||''} onChange={e=>setExamForm({...examForm,conclusion:e.target.value})}><option value="">-</option><option>Normal</option><option>Perlu pemantauan</option><option>Perlu pemeriksaan lanjutan</option><option>Perlu rujukan</option></select></label><label className="field"><span>Keluhan</span><textarea value={examForm.complaints||''} onChange={e=>setExamForm({...examForm,complaints:e.target.value})}/></label><label className="field"><span>Riwayat Penyakit</span><textarea value={examForm.diseaseHistory||''} onChange={e=>setExamForm({...examForm,diseaseHistory:e.target.value})}/></label><label className="field"><span>Obat yang sedang dikonsumsi</span><textarea value={examForm.currentMedication||''} onChange={e=>setExamForm({...examForm,currentMedication:e.target.value})}/></label><label className="field"><span>Catatan</span><textarea value={examForm.notes||''} onChange={e=>setExamForm({...examForm,notes:e.target.value})}/></label><div className="panel" style={{gridColumn:'1/-1'}}><h4>Obat yang Diberikan</h4><p className="muted">Tambahkan obat bila ada; aturan penggunaan tidak dicatat di modul ini.</p><div className="form-grid"><label className="field"><span>Nama Obat</span><input value={examForm.medicineName||''} onChange={e=>setExamForm({...examForm,medicineName:e.target.value})}/></label>{f('quantity','Jumlah','number')}<label className="field"><span>Satuan</span><input value={examForm.unit||''} onChange={e=>setExamForm({...examForm,unit:e.target.value})}/></label>{f('medicationNotes','Keterangan')} </div></div><div className="actions"><button onClick={()=>{const medications=examForm.medicineName?[{medicineName:examForm.medicineName,quantity:examForm.quantity,unit:examForm.unit,notes:examForm.medicationNotes}]:[];saveExamWithMedications(medications)}}>Simpan Pemeriksaan</button><button className="secondary" onClick={()=>setShowExam(false)}>Batal</button></div></div></div>}
 </div>;
 async function saveExamWithMedications(medications:any[]){try{const body={...examForm,medications};delete body.medicineName;delete body.quantity;delete body.unit;delete body.medicationNotes;await api('/health/profiles/'+selected.id+'/exams',{method:'POST',body:JSON.stringify(body)});setMsg('Pemeriksaan berhasil disimpan.');setExamForm({});setShowExam(false);open(selected.id);load()}catch(e:any){setMsg(e.message)}}
}

function PTM(){const[periods,setPeriods]=useState<any[]>([]),[period,setPeriod]=useState(''),[rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[sort,setSort]=useState('diseaseName');useEffect(()=>{api('/periods').then(r=>{setPeriods(r);if(r[0])setPeriod(r[0].id)})},[]);useEffect(()=>{if(period)api('/ptm/summary?periodId='+period).then(setRows)},[period]);const filtered=useMemo(()=>rows.filter(r=>`${r.diseaseName} ${r.LAMA} ${r.BARU} ${r.total}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==='diseaseName'?a.diseaseName.localeCompare(b.diseaseName,'id'):Number(b[sort]||0)-Number(a[sort]||0)),[rows,q,sort]);return <div className="page"><div className="toolbar"><select value={period} onChange={e=>setPeriod(e.target.value)}>{periods.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></div><div className="panel"><h3>Rekap Penyakit Tidak Menular</h3><TableTools search={q} setSearch={setQ} sort={sort} setSort={setSort} placeholder="Cari nama penyakit..." options={[{value:'diseaseName',label:'Nama penyakit'},{value:'total',label:'Total terbesar'},{value:'BARU',label:'Kasus baru terbesar'},{value:'LAMA',label:'Kasus lama terbesar'}]}/><div className="scroll"><table><thead><tr><th>Penyakit</th><th>Lama</th><th>Baru</th><th>Total</th></tr></thead><tbody>{filtered.map(r=><tr key={r.diseaseName}><td>{r.diseaseName}</td><td>{r.LAMA}</td><td>{r.BARU}</td><td><b>{r.total}</b></td></tr>)}{!filtered.length&&<tr><td colSpan={4}>Tidak ada data yang sesuai.</td></tr>}</tbody></table></div></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
